services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8333:8333"
    expose:
      - "8333"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - YOLO_VERBOSE=False


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8333
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8333
    depends_on:
      - backend
